### ISSUE TITLE
WSSE authentication failed FOSUserBundle

### ISSUE THREAD

**Issue by sergiu-popa** [escapestudios/EscapeWSSEAuthenticationBundle#56]
I installed this bundle but I get WSSE authentication failed on dev.log file. This is my configuration:
```
security:
  providers:
    fos_userbundle:
      id: fos_user.user_provider.username_email

  encoders:
    FOS\UserBundle\Model\UserInterface: sha512

  firewalls: #important! user same tab size :)
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    wsse_secured:
      pattern:   ^/api/.*
      wsse:
        realm: "Secured with WSSE" #identifies the set of resources to which the authentication information will apply (WWW-Authenticate)
        profile: "UsernameToken" #WSSE profile (WWW-Authenticate)
        provider: fos_userbundle
        encoder: #digest algorithm
          algorithm: sha1
          encodeHashAsBase64: true
          iterations: 512
```
I'm using this tool to generate the WSSE Header: http://www.teria.com/~koseki/tools/wssegen/ and for the password I'm using the encrypted salt concatenated with the password as it is in the database. What's the problem? I'm using Chrome's Extension REST Console.

Thank you
